Update ppc64le-runtime.yaml

diff --git a/.github/workflows/ppc64le-runtime.yaml b/.github/workflows/ppc64le-runtime.yaml
--- a/.github/workflows/ppc64le-runtime.yaml
+++ b/.github/workflows/ppc64le-runtime.yaml
@@ -264,108 +264,108 @@ jobs:
       #     git commit -m "Add ppc64le workflow status summary" || echo "No changes to commit"
       #     git push
 
-      - name: Create or update HTML report
-        run: |
-          REPORT=".github/ppc64le/report.html"
+      # - name: Create or update HTML report
+      #   run: |
+      #     REPORT=".github/ppc64le/report.html"
       
-          mkdir -p "$(dirname "$REPORT")"
+      #     mkdir -p "$(dirname "$REPORT")"
       
-          # Create base HTML if file does not exist
-          if [[ ! -s "$REPORT" ]]; then
-            cat <<'EOF' > "$REPORT"
-          <!DOCTYPE html>
-          <html lang="en">
-          <head>
-              <meta charset="UTF-8">
-              <title>Build Status Report</title>
-              <style>
-                  body { font-family: Arial, sans-serif; padding: 20px; }
-                  table { width: 100%; border-collapse: collapse; }
-                  th, td { border: 1px solid #333; padding: 10px; vertical-align: top; }
-                  th { background-color: #f2f2f2; }
-                  .success { background-color: #e6f9e6; color: #1b5e20; }
-                  .failure { background-color: #fdeaea; color: #8a1c1c; }
-                  .status hr { margin: 10px 0; }
-                  .status-grid {
-                      display: grid;
-                      grid-template-columns: auto 1fr auto 1fr;
-                      gap: 6px 20px;
-                      margin-top: 5px;
-                  }
-                  .label { font-weight: bold; }
-              </style>
-          </head>
-          <body>
-          <h2>Report</h2>
-          <table>
-          <thead>
-          <tr>
-          <th>Date</th>
-          <th>Start Time</th>
-          <th>End Time</th>
-          <th>Status</th>
-          </tr>
-          </thead>
-          <tbody>
-          </tbody>
-          </table>
+      #     # Create base HTML if file does not exist
+      #     if [[ ! -s "$REPORT" ]]; then
+      #       cat <<'EOF' > "$REPORT"
+      #     <!DOCTYPE html>
+      #     <html lang="en">
+      #     <head>
+      #         <meta charset="UTF-8">
+      #         <title>Build Status Report</title>
+      #         <style>
+      #             body { font-family: Arial, sans-serif; padding: 20px; }
+      #             table { width: 100%; border-collapse: collapse; }
+      #             th, td { border: 1px solid #333; padding: 10px; vertical-align: top; }
+      #             th { background-color: #f2f2f2; }
+      #             .success { background-color: #e6f9e6; color: #1b5e20; }
+      #             .failure { background-color: #fdeaea; color: #8a1c1c; }
+      #             .status hr { margin: 10px 0; }
+      #             .status-grid {
+      #                 display: grid;
+      #                 grid-template-columns: auto 1fr auto 1fr;
+      #                 gap: 6px 20px;
+      #                 margin-top: 5px;
+      #             }
+      #             .label { font-weight: bold; }
+      #         </style>
+      #     </head>
+      #     <body>
+      #     <h2>Report</h2>
+      #     <table>
+      #     <thead>
+      #     <tr>
+      #     <th>Date</th>
+      #     <th>Start Time</th>
+      #     <th>End Time</th>
+      #     <th>Status</th>
+      #     </tr>
+      #     </thead>
+      #     <tbody>
+      #     </tbody>
+      #     </table>
           
-          </body>
-          </html>
-          EOF
-              fi
-          DATE=$(TZ=Asia/Kolkata date +"%d/%m/%Y")
-          START_TIME="${{ needs.ppc64le-sync.outputs.workflow_start_time }}"
-          END_TIME=$(TZ=Asia/Kolkata date +"%I:%M %p")
-          BUILD_STATUS="${{ needs.ppc64le-runtime-build-test.result }}"
-          TEST_STATUS="${{ needs.ppc64le-runtime-build-test.result }}"
-          if [[ "$BUILD_STATUS" == "success" && "$TEST_STATUS" == "success" ]]; then
-            ROW_CLASS="success"
-            STATUS_MSG="Runtime build is successful, test result"
-          else
-            ROW_CLASS="failure"
-            STATUS_MSG="Runtime build or test failed"
-          fi
+      #     </body>
+      #     </html>
+      #     EOF
+      #         fi
+      #     DATE=$(TZ=Asia/Kolkata date +"%d/%m/%Y")
+      #     START_TIME="${{ needs.ppc64le-sync.outputs.workflow_start_time }}"
+      #     END_TIME=$(TZ=Asia/Kolkata date +"%I:%M %p")
+      #     BUILD_STATUS="${{ needs.ppc64le-runtime-build-test.result }}"
+      #     TEST_STATUS="${{ needs.ppc64le-runtime-build-test.result }}"
+      #     if [[ "$BUILD_STATUS" == "success" && "$TEST_STATUS" == "success" ]]; then
+      #       ROW_CLASS="success"
+      #       STATUS_MSG="Runtime build is successful, test result"
+      #     else
+      #       ROW_CLASS="failure"
+      #       STATUS_MSG="Runtime build or test failed"
+      #     fi
       
-          TOTAL=246
-          PASSED="243 (98.00%)"
-          FAILED="0 (0%)"
-          SKIPPED="3 (1.00%)"
+      #     TOTAL=246
+      #     PASSED="243 (98.00%)"
+      #     FAILED="0 (0%)"
+      #     SKIPPED="3 (1.00%)"
       
-          ROW=$(cat <<EOF
-      <tr class="$ROW_CLASS">
-      <td>$DATE</td>
-      <td>$START_TIME</td>
-      <td>$END_TIME</td>
-      <td class="status">
-      $STATUS_MSG
-      <hr>
-      <div class="status-grid">
-      <div class="label">Total Test Cases :</div><div>$TOTAL</div>
-      <div class="label">Test Passed :</div><div>$PASSED</div>
-      <div class="label">Test Failed :</div><div>$FAILED</div>
-      <div class="label">Test Skipped :</div><div>$SKIPPED</div>
-      </div>
-      </td>
-      </tr>
-      EOF
-          )
+      #     ROW=$(cat <<EOF
+      # <tr class="$ROW_CLASS">
+      # <td>$DATE</td>
+      # <td>$START_TIME</td>
+      # <td>$END_TIME</td>
+      # <td class="status">
+      # $STATUS_MSG
+      # <hr>
+      # <div class="status-grid">
+      # <div class="label">Total Test Cases :</div><div>$TOTAL</div>
+      # <div class="label">Test Passed :</div><div>$PASSED</div>
+      # <div class="label">Test Failed :</div><div>$FAILED</div>
+      # <div class="label">Test Skipped :</div><div>$SKIPPED</div>
+      # </div>
+      # </td>
+      # </tr>
+      # EOF
+      #     )
       
-          TMP=$(mktemp)
-          echo "$ROW" > "$TMP"
-          sed -i "/<tbody>/r $TMP" "$REPORT"
-          rm -f "$TMP"
+      #     TMP=$(mktemp)
+      #     echo "$ROW" > "$TMP"
+      #     sed -i "/<tbody>/r $TMP" "$REPORT"
+      #     rm -f "$TMP"
       
-          echo "HTML report updated:"
-          grep -n "<tr" "$REPORT"
+      #     echo "HTML report updated:"
+      #     grep -n "<tr" "$REPORT"
 
-      - name: Commit report
-        run: |
-          git config user.name "github-app[bot]"
-          git config user.email "github-app[bot]@users.noreply.github.com"
-          git add .github/ppc64le/report.html
-          git commit -m "Update ppc64le build report" || echo "No changes"
-          git push
+      # - name: Commit report
+      #   run: |
+      #     git config user.name "github-app[bot]"
+      #     git config user.email "github-app[bot]@users.noreply.github.com"
+      #     git add .github/ppc64le/report.html
+      #     git commit -m "Update ppc64le build report" || echo "No changes"
+      #     git push
 
 
     
