hello 7

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -33,11 +33,11 @@ jobs:
       - name: Run the script
         run: |
           set -e
-          docker exec github-api bash -c "chmod +x /runtime.sh && /runtime.sh --ref workFlow" 2>&1 | tee /tmp/script.log
-          exit_code=${PIPESTATUS[0]}
-          echo "Script exited with code $exit_code"
+          docker exec github-api bash -c "chmod +x /runtime.sh && /runtime.sh --ref workFlow" > /tmp/script.log 2>&1
+          exit_code=$?
+          cat /tmp/script.log
           if [ "$exit_code" -ne 0 ]; then
-            echo "Script failed"
+            echo "::error ::/runtime.sh failed with exit code $exit_code"
             exit $exit_code
           fi
 
